### ISSUE TITLE
Based on offline-issues

### ISSUE THREAD

**Issue by vmx** [jiapantw/export-github-issues#1]
I was looking for a tool to export GitHub issues to Markdown. There are several ones out there. Another one is https://github.com/jlord/offline-issues. Your code is quite similar, so it would be great if you could indicate that your project is based on the work of https://github.com/jlord/offline-issues.

**Comment by justintien** [comment]
@vmx Yes, this is based on https://github.com/jlord/offline-issues, I updated README, and LICENSE

**Comment by vmx** [comment]
Thanks a lot, that's perfect!
